services:
  - type: web
    name: tomato-disease-app
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MODEL_PATH
        value: models/tomato_model.onnx
      - key: CONF_THRESH
        value: "0.60"
      - key: DEBUG_MODE
        value: "false"
